// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SSMSPlus
{
    internal sealed partial class Vsix
    {
        public const string Id = "SSMSPlus.54c59ded-53cd-43d4-915a-6a304411353a";
        public const string Name = "SSMSPlus";
        public const string Description = @"SSMS Plus for Visual Studio 2016";
        public const string Language = "en-US";
        public const string Version = "1.15";
        public const string Author = "Company";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
